version: '3'

networks:
  adonis:

services:
  db:
    image: mariadb:latest
    container_name: docker-adonis-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker-adonis
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    networks:
      - adonis

  api:
    container_name: docker-adonis-api
    build:
      context: .
      dockerfile: adonis.dockerfile
    command: >
      sh -c "yarn &&
            node ace serve --watch"
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/api
    networks:
      - adonis
    links:
      - db

  client:
    container_name: docker-adonis-client
    build:
      context: .
      dockerfile: client.dockerfile
    command: >
      sh -c "yarn &&
            yarn serve"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/client
    networks:
      - adonis